roles:
  - master
  - worker

ntpServers:
  - ntp1.hetzner.de
  - ntp2.hetzner.de
  - ntp3.hetzner.de

chronyConfig: |-
  {{- range .Values.ntpServers }}
  server {{ . }} iburst
  {{- end }}

  stratumweight 0
  driftfile /var/lib/chrony/drift
  rtcsync
  makestep 10 3
  bindcmdaddress 127.0.0.1
  bindcmdaddress ::1
  keyfile /etc/chrony.keys
  commandkey 1
  generatecommandkey
  noclientlog
  logchange 0.5
  logdir /var/log/chrony
