kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

generatorOptions:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: ServerSideApply=true

resources:
  - ../../base
  - htpasswd-es.yaml

patches:
  - path: patch-htpasswd-auth.yaml
    target:
      group: config.openshift.io
      kind: OAuth
      name: cluster
      version: v1
