kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ../github
  - gitlab-client-es.yaml

patches:
  - path: patch-gitlab-oauth.yaml
    target:
      group: config.openshift.io
      kind: OAuth
      name: cluster
      version: v1
