dex:
  replicaCount: 1

  commonLabels:
    app.kubernetes.io/part-of: argo-workflows

  image:
    repository: ghcr.io/dexidp/dex
    pullPolicy: IfNotPresent

  https:
    enabled: false

  grpc:
    enabled: true

  configSecret:
    create: true
    name: "dex-server-secret"

  envVars:
    - name: DEX_OAUTH_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: dex-sa-token
          key: token

    - name: ARGO_WORKFLOWS_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: argo-wf-dex
          key: token

  config:
    issuer: https://dex-server-argo-workflows.apps.ocp4.whatever.out-of-my-head.de/api/dex
    storage:
      type: memory
    web:
      http: "0.0.0.0:5556"
    grpc:
      addr: "0.0.0.0:5557"
    oauth2:
      skipApprovalScreen: true
    staticClients:
      - id: argo-workflows
        name: argo-workflows
        secretEnv: ARGO_WORKFLOWS_CLIENT_SECRET
        redirectURIs:
          - https://argo-workflows-server-argo-workflows.apps.ocp4.whatever.out-of-my-head.de/oauth2/callback
    connectors:
      - type: openshift
        id: openshift
        name: OpenShift
        config:
          issuer: https://kubernetes.default.svc
          clientID: system:serviceaccount:argo-workflows:dex-server
          clientSecret: $DEX_OAUTH_CLIENT_SECRET
          insecureCA: true
          groups: []
          redirectURI: https://dex-server-argo-workflows.apps.ocp4.whatever.out-of-my-head.de/api/dex/callback

  serviceAccount:
    create: false
    name: dex-server

  rbac:
    create: true
    createClusterScoped: true

  podSecurityContext:
    # capabilities:
    #     drop:
    #       - ALL
    runAsNonRoot: true
    # allowPrivilegeEscalation: false

  securityContext:
    seccompProfile:
      type: RuntimeDefault

  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 500m
      memory: 256Mi

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%

  serviceMonitor:
    enabled: true
