apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-client-secret
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: github-client-secret
  data:
    - secretKey: clientSecret
      remoteRef:
        key: github-client-secret
        property: clientSecret
