kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

generatorOptions:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: ServerSideApply=true 

resources:
  - github-client-es.yaml

patches:
  - path: patch-github-oauth.yaml
    target:
      group: config.openshift.io
      kind: OAuth
      name: cluster
      version: v1
