apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: openshift-cert-manager
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/cluster-config/cert-manager-operator/operator/base
    repoURL: https://github.com/StinkyBenji/ocp-out-of-my-head.git
    targetRevision: main
  syncPolicy:
    automated: 
      prune: false
      selfHeal: true
      