apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hashicorp-vault
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    chart: vault
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.24.1
    helm:
      releaseName: vault
      values: |
        global:
          openshift: true
        dev:
          enabled: true
        ui:
          enabled: true
        injector:
          image:
            repository: "registry.connect.redhat.com/hashicorp/vault-k8s"
            tag: "1.2.1-ubi"
        agentImage:
          repository: "registry.connect.redhat.com/hashicorp/vault"
          tag: "1.13.1-ubi"
        server:
          route: 
            enabled: true
          image:
            repository: "registry.connect.redhat.com/hashicorp/vault"
            tag: "1.13.1-ubi"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: hashicorp-vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
