apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oauth
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    namespace: openshift-config
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/cluster-config/oauth/overlays/gitlab
    repoURL: https://github.com/StinkyBenji/ocp-out-of-my-head.git
    targetRevision: main
  syncPolicy:
    automated: {}