apiVersion: config.openshift.io/v1
kind: APIServer
metadata:
  name: cluster
spec:
  audit:
    profile: Default
  servingCerts:
    namedCertificates:
    - names:
      - api.ocp4.whatever.out-of-my-head.de 
      servingCertificate:
        name: openshift-api-certificate
