apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true,SkipDryRunOnMissingResource=true

resources:
  - openshift-wildcard-certificate.yaml
  - openshift-api-certificate.yaml
  - apiserver.yaml
  - ingress.yaml
