apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hetzner-api-token
  namespace: cert-manager
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: hetzner-api-token
  data:
    - secretKey: api-key
      remoteRef:
        key: hetzner-api-token
        property: api-key
