apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hetzner-api-token
  namespace: openshift-cert-manager
spec:
  encryptedData:
    api-token: AgACrkdN6Svv3vppc8s/KKSRY7n5gbw0oqt9pAp593FOpkMJp2is6nfiQn8XikF58lCjA8Om+U4usvOhWT6QgxMDpX5FfqL7Bp/psgusCZsck3z6azZzunhOlsZFasLH3CNJyTtcs4zovfCK2HhZNjVH7zi1Eap9HxhLvbbv6OeEUTKTyf6S9BajqHaMlWoQjR9VROC8s8083JbWR+bOyvtyIYG6GRWbZpP0Rn72kACAm8fId1tpIvuuUSgOHjEfiSbTx9duZqjVyL6KcOWUmKXK+XXVoNzR7AfQ2eJErUiQjVJZzKI85D8q5AGZubcAmkmkUAHRzdNZShxTTMeViDyfaAC1Bp24n+bGWO/N7vQQYUgFsaItx5jnhAw7eWv3/6Fxc+Z4dL1pXreb/BBqpXovK/lYGXO0xpvMXIQCNByrRu+IBDPyPDkQuSdTWjTHJmmtr+SO3YbZYQtSR2REqv9sNRMAqCF0mIyJrSjofHjRPTRWkUeccvRBxgpuKvd7TW3xuOPmpUqMSblxdTZ0K1CqfyRBjj7Zm1ffxhExpfI3EKcEL0MCSH3lh2Ji0Ntbdx1GNqg1f3uCLKAGkFaRUyPL+qnG9vJcb3rJmnsHJVe6fmRCLOa3VR9h3/ryMkfV00kUyCMwAoJEpqJGSkoHgyp5Mb2QeuyyAMlQ+N93hNAp8gbdJ7I4LHyyt/MsjEiG6/N81OXPRBlqlehHkuJ0HCyRQNCWVsxV7A3jVpfqcqaR6A==
  template:
    metadata:
      creationTimestamp: null
      name: hetzner-api-token
      namespace: openshift-cert-manager
    type: Opaque

