apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: "rzh@redhat.com"
    privateKeySecretRef:
      name: letsencrypt-account-key
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
        webhook:
          groupName: ocp4.whatever.out-of-my-head.de
          solverName: hetzner
          config:
            secretName: hetzner-api-token
            # zoneName: out-of-my-head.de
            apiUrl: https://dns.hetzner.com/api/v1
