apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openshift-wildcard-certificate
  namespace: openshift-ingress
spec:
  duration: 1440h0m0s
  renewBefore: 360h0m0s
  commonName: '*.apps.ocp4.whatever.out-of-my-head.de'
  dnsNames:
    - '*.apps.ocp4.whatever.out-of-my-head.de'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: openshift-wildcard-certificate