ocp_namespace:
  name: prod-ns
  description: "A namespace for production"
  annotations:
    app: demo
  labels:
    owner: StinkyBenji
  rbac:
    - role: admin
      kind: user
      name: StinkyBenji
  networkPolicy:
    enabled: true
