apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-webhook-hetzner
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    chart: cert-manager-webhook-hetzner
    repoURL: https://vadimkim.github.io/cert-manager-webhook-hetzner
    targetRevision: 1.2.1
    helm:
      values: |
        groupName: ocp4.whatever.out-of-my-head.de
        certManager:
          namespace: openshift-cert-manager
          serviceAccountName: cert-manager
        secretName:
          - hetzner-api-token
        podSecurityContext:
          runAsGroup: 
          runAsUser: 
  destination:
    server: "https://kubernetes.default.svc"
    namespace: openshift-cert-manager
  syncPolicy:
    automated: {}
