apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-webhook-app
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    path: deploy/cert-manager-webhook-hetzner
    repoURL: https://github.com/vadimkim/cert-manager-webhook-hetzner
    targetRevision: master
    helm:
      values: |
        groupName: ocp4.whatever.out-of-my-head.de
  destination:
    server: "https://kubernetes.default.svc"
    namespace: openshift-cert-manager
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
