---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: linters
  annotations:
    pipelinesascode.tekton.dev/on-event: "[push, pull_request]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/max-keep-runs: "2"
    pipelinesascode.tekton.dev/task: "[git-clone]"
spec:
  params:
    - name: repo_url
      value: "{{repo_url}}"
    - name: revision
      value: "{{revision}}"
  pipelineSpec:
    params:
      - name: repo_url
      - name: revision
    tasks:
      - name: fetch-repository
        params:
          - name: url
            value: "$(params.repo_url)"
          - name: revision
            value: "$(params.revision)"
        taskRef:
          name: git-clone
        workspaces:
          - name: output
            workspace: shared-workspace

      - name: yamllint
        runAfter:
          - fetch-repository
        workspaces:
          - name: shared-workspace
            workspace: shared-workspace
        taskSpec:
          workspaces:
            - name: shared-workspace
          steps:
            - name: yaml-lint
              image: docker.io/cytopia/yamllint:latest
              workingDir: $(workspaces.shared-workspace.path)
              script: |
                set -x
                yamllint -c .yamllint $(find . -type f -regex ".*y[a]ml" -print)

      - name: shellcheck
        runAfter:
          - fetch-repository
        workspaces:
          - name: shared-workspace
            workspace: shared-workspace
        taskSpec:
          workspaces:
            - name: shared-workspace
          steps:
            - name: shellcheck
              image: docker.io/koalaman/shellcheck:v0.7.1
              workingDir: $(workspaces.shared-workspace.path)
              script: |
                set -x
                shellcheck --shell=bash $(find . -type f -regex ".*sh" -print)

  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
