apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: groups-and-membership
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/cluster-config/groups-roles-bindings/base
    repoURL: https://github.com/StinkyBenji/ocp-out-of-my-head.git
    targetRevision: main