apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-oauth-client-secret
  namespace: openshift-config
spec:
  encryptedData:
    clientSecret: AgCnsuQXrROrcWTNb6ttgzvGj6iZGQznQ+EG3FiQRUTjpQ+GQL6n6vFVILCOJyqWDpZR4+Z4bCYOck1V3vfJviOtWg2jDUz4zbQZdIqT/Zy4s0Z6T5+oacn8ximA1OkvKitS+S66bUKoIzkRJTVBVg6ghn49wIuBp5IN6DEscTDaBbtvQBxTBQCfbJUQQagqa5zL01eNY/svVi4zclpIFCFi2HkAuDl+N4Sqon3iramyAgc8oSRbKOW9QohF3McU6KFzEKFfMy63xTsZ10OTlC5IcimZnKvRiWKPmkMzs/BSJe5E/Kga9wG+2fz0zvP5yX2leMzaqRmz7DNjd/C+hx81PAQVnvQyWZxeDPn3IYYpvb6sIlgG5XB2Z1LhnsfVk4IGJHsy75PZmFsgIZDxlQQW1MeNdoGz2u/S6axtgBQu7R/buyuDVGN9mXrpHYXG/MR9KxeBCdLzqXuYjnzrU11fEXldVsDd1q4TMTY5aGYV0vha6LJjZ4OYaMqVwPwch2UjhABophooIATsuWNoDSEZEy81BPnBetVr5bE/Grz6G2KRiuv58TjvvJtx2+xYhPmZ5DqQSj6hkq4cu2wzA99cU691pvAjSIpYLhUkYX9Edlu68wEwq1xTqN03pkvF78kAlUgrh0YgUE6fxDON4yHUjEAZV7Cvunf9VwgdOsHApIRerglgQP8vsPCoPbXkcV5PkLW9O4h0B7sjr7D0T+tWknLfw4kSHa1HJP/vGgMAKa7AURIOGPVs
  template:
    metadata:
      creationTimestamp: null
      name: github-oauth-client-secret
      namespace: openshift-config
    type: Opaque

