apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.8.1
    helm:
      releaseName: external-secrets
      values: |
        prometheus:
          enabled: true
          service:
            port: 8080
        resources:
          requests:
            cpu: 10m
            memory: 96Mi
          limits:
            cpu: 100m
            memory: 256Mi
  destination:
    server: "https://kubernetes.default.svc"
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
